### ISSUE TITLE
[BUG/Help] bash train.sh报错CUDA Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by zqkou** [THUDM/ChatGLM2-6B#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

bash train.sh报错CUDA Error: no kernel image is available for execution on the device

=========
train.sh
=========
```
PRE_SEQ_LEN=128
LR=2e-2
NUM_GPUS=2

torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS main.py \
    --do_train \
    --train_file /data/ptuning/AdvertiseGen/train.json \
    --validation_file /data/ptuning/AdvertiseGen/dev.json \
    --preprocessing_num_workers 10 \
    --prompt_column content \
    --response_column summary \
    --overwrite_cache \
    --model_name_or_path /data/model \
    --output_dir output/adgen-chatglm2-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 64 \
    --max_target_length 128 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 3000 \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \
    --quantization_bit 4
```

运行 bash.trains.sh, 报错如下：
```
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
07/10/2023 08:27:18 - WARNING - __main__ - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: False
07/10/2023 08:27:18 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
07/10/2023 08:27:18 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=16,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.02,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=output/adgen-chatglm2-6b-pt-128-2e-2/runs/Jul10_08-27-18_r64a78428ced2281ef01aef5b-gpu-jupyter-7d86bd58f9-gjjh9,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=3000,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=3.0,
optim=adamw_hf,
optim_args=None,
output_dir=output/adgen-chatglm2-6b-pt-128-2e-2,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
predict_with_generate=True,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['tensorboard'],
resume_from_checkpoint=None,
run_name=output/adgen-chatglm2-6b-pt-128-2e-2,
save_on_each_node=False,
save_steps=1000,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
07/10/2023 08:27:19 - WARNING - datasets.builder - Found cached dataset json (/home/jovyan/.cache/huggingface/datasets/json/default-93e47435b02a32f3/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 81.53it/s]
07/10/2023 08:27:19 - WARNING - datasets.builder - Found cached dataset json (/home/jovyan/.cache/huggingface/datasets/json/default-93e47435b02a32f3/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 248.49it/s]
[INFO|configuration_utils.py:666] 2023-07-10 08:27:19,395 >> loading configuration file /data/model/config.json
[WARNING|configuration_auto.py:905] 2023-07-10 08:27:19,395 >> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
[WARNING|configuration_auto.py:905] 2023-07-10 08:27:19,395 >> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|configuration_utils.py:666] 2023-07-10 08:27:19,530 >> loading configuration file /data/model/config.json
[INFO|configuration_utils.py:720] 2023-07-10 08:27:19,531 >> Model config ChatGLMConfig {
  "_name_or_path": "/data/model",
  "add_bias_linear": false,
  "add_qkv_bias": true,
  "apply_query_key_layer_scaling": true,
  "apply_residual_connection_post_layernorm": false,
  "architectures": [
    "ChatGLMModel"
  ],
  "attention_dropout": 0.0,
  "attention_softmax_in_fp32": true,
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bias_dropout_fusion": true,
  "eos_token_id": 2,
  "ffn_hidden_size": 13696,
  "fp32_residual_connection": false,
  "hidden_dropout": 0.0,
  "hidden_size": 4096,
  "kv_channels": 128,
  "layernorm_epsilon": 1e-05,
  "model_type": "chatglm",
  "multi_query_attention": true,
  "multi_query_group_num": 2,
  "num_attention_heads": 32,
  "num_layers": 28,
  "original_rope": true,
  "pad_token_id": 0,
  "padded_vocab_size": 65024,
  "post_layer_norm": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "rmsnorm": true,
  "seq_length": 32768,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.27.1",
  "use_cache": true,
  "vocab_size": 65024
}

[WARNING|tokenization_auto.py:652] 2023-07-10 08:27:19,538 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[WARNING|tokenization_auto.py:652] 2023-07-10 08:27:19,539 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|tokenization_utils_base.py:1800] 2023-07-10 08:27:19,667 >> loading file tokenizer.model
[INFO|tokenization_utils_base.py:1800] 2023-07-10 08:27:19,667 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1800] 2023-07-10 08:27:19,667 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1800] 2023-07-10 08:27:19,667 >> loading file tokenizer_config.json
[WARNING|auto_factory.py:456] 2023-07-10 08:27:19,712 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
07/10/2023 08:27:19 - INFO - __main__ - model_args.ptuning_checkpoint is None
[WARNING|auto_factory.py:456] 2023-07-10 08:27:19,721 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/.cache/huggingface/modules/transformers_modules/model/modeling_chatglm.py'
[INFO|modeling_utils.py:2400] 2023-07-10 08:27:19,897 >> loading weights file /data/model/pytorch_model.bin.index.json
[INFO|configuration_utils.py:575] 2023-07-10 08:27:19,904 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "eos_token_id": 2,
  "pad_token_id": 0,
  "transformers_version": "4.27.1"
}

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████| 7/7 [01:13<00:00, 10.49s/it]
[WARNING|modeling_utils.py:3034] 2023-07-10 08:28:33,478 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /data/model and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Quantized to 4 bit
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████| 7/7 [01:13<00:00, 10.49s/it]
[INFO|modeling_utils.py:3032] 2023-07-10 08:28:33,542 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[WARNING|modeling_utils.py:3034] 2023-07-10 08:28:33,542 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /data/model and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:2690] 2023-07-10 08:28:33,546 >> Generation config file not found, using a generation config created from the model config.
Quantized to 4 bit
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/ptuning/main.py:487 in <module>                                                            │
│                                                                                                  │
│   484                                                                                            │
│   485                                                                                            │
│   486 if __name__ == "__main__":                                                                 │
│ ❱ 487 │   main()                                                                                 │
│   488                                                                                            │
│                                                                                                  │
│ /data/ptuning/main.py:202 in main                                                                │
│                                                                                                  │
│   199 │                                                                                          │
│   200 │   if model_args.quantization_bit is not None:                                            │
│   201 │   │   print(f"Quantized to {model_args.quantization_bit} bit")                           │
│ ❱ 202 │   │   model = model.quantize(model_args.quantization_bit)                                │
│   203 │   if model_args.pre_seq_len is not None:                                                 │
│   204 │   │   # P-tuning v2                                                                      │
│   205 │   │   model = model.half()                                                               │
│                                                                                                  │
│ /home/jovyan/.cache/huggingface/modules/transformers_modules/model/modeling_chatglm.py:1190 in   │
│ quantize                                                                                         │
│                                                                                                  │
│   1187 │   │                                                                                     │
│   1188 │   │   self.config.quantization_bit = bits                                               │
│   1189 │   │                                                                                     │
│ ❱ 1190 │   │   self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=e  │
│   1191 │   │   │   │   │   │   │   │   │   │   │   **kwargs)                                     │
│   1192 │   │   return self                                                                       │
│   1193                                                                                           │
│                                                                                                  │
│ /home/jovyan/.cache/huggingface/modules/transformers_modules/model/quantization.py:155 in        │
│ quantize                                                                                         │
│                                                                                                  │
│   152 def quantize(model, weight_bit_width, empty_init=False, device=None):                      │
│   153 │   """Replace fp16 linear with quantized linear"""                                        │
│   154 │   for layer in model.layers:                                                             │
│ ❱ 155 │   │   layer.self_attention.query_key_value = QuantizedLinear(                            │
│   156 │   │   │   weight_bit_width=weight_bit_width,                                             │
│   157 │   │   │   weight=layer.self_attention.query_key_value.weight.to(torch.cuda.current_dev   │
│   158 │   │   │   bias=layer.self_attention.query_key_value.bias,                                │
│                                                                                                  │
│ /home/jovyan/.cache/huggingface/modules/transformers_modules/model/quantization.py:139 in        │
│ __init__                                                                                         │
│                                                                                                  │
│   136 │   │   │   self.weight_scale = weight.abs().max(dim=-1).values / ((2 ** (weight_bit_wid   │
│   137 │   │   │   self.weight = torch.round(weight / self.weight_scale[:, None]).to(torch.int8   │
│   138 │   │   │   if weight_bit_width == 4:                                                      │
│ ❱ 139 │   │   │   │   self.weight = compress_int4_weight(self.weight)                            │
│   140 │   │                                                                                      │
│   141 │   │   self.weight = Parameter(self.weight.to(device), requires_grad=False)               │
│   142 │   │   self.weight_scale = Parameter(self.weight_scale.to(device), requires_grad=False)   │
│                                                                                                  │
│ /home/jovyan/.cache/huggingface/modules/transformers_modules/model/quantization.py:78 in         │
│ compress_int4_weight                                                                             │
│                                                                                                  │
│    75 │   │   gridDim = (n, 1, 1)                                                                │
│    76 │   │   blockDim = (min(round_up(m, 32), 1024), 1, 1)                                      │
│    77 │   │                                                                                      │
│ ❱  78 │   │   kernels.int4WeightCompression(                                                     │
│    79 │   │   │   gridDim,                                                                       │
│    80 │   │   │   blockDim,                                                                      │
│    81 │   │   │   0,                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/kernels/base.py:48 in __call__                │
│                                                                                                  │
│   45 │   │   │   sharedMemBytes : int, stream : cudart.cudaStream_t, params : List[Any] ) ->     │
│   46 │   │   assert len(gridDim) == 3                                                            │
│   47 │   │   assert len(blockDim) == 3                                                           │
│ ❱ 48 │   │   func = self._prepare_func()                                                         │
│   49 │   │                                                                                       │
│   50 │   │   cuda.cuLaunchKernel(func,                                                           │
│   51 │   │   │   gridDim[0], gridDim[1], gridDim[2],                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/kernels/base.py:40 in _prepare_func           │
│                                                                                                  │
│   37 │   │   cudart.cudaSetDevice(curr_device)   # ensure cudart context                         │
│   38 │   │   if curr_device not in self._funcs:                                                  │
│   39 │   │   │   self._funcs[curr_device] = cuda.cuModuleGetFunction(                            │
│ ❱ 40 │   │   │   │   self._module.get_module(), self._func_name                                  │
│   41 │   │   │   )                                                                               │
│   42 │   │   return self._funcs[curr_device]                                                     │
│   43                                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/kernels/base.py:24 in get_module              │
│                                                                                                  │
│   21 │   │   curr_device = cudart.cudaGetDevice()                                                │
│   22 │   │   if curr_device not in self._module:                                                 │
│   23 │   │   │   Device(curr_device).use()   # force initialize context                          │
│ ❱ 24 │   │   │   self._module[curr_device] = cuda.cuModuleLoadData(self._code)                   │
│   25 │   │   return self._module[curr_device]                                                    │
│   26                                                                                             │
│   27                                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/library/base.py:94 in wrapper                 │
│                                                                                                  │
│   91 │   │   │   def decorator(f):                                                               │
│   92 │   │   │   │   @wraps(f)                                                                   │
│   93 │   │   │   │   def wrapper(*args, **kwargs):                                               │
│ ❱ 94 │   │   │   │   │   return f(*args, **kwargs)                                               │
│   95 │   │   │   │   return wrapper                                                              │
│   96 │   │   │   return decorator                                                                │
│   97                                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/library/cuda.py:233 in cuModuleLoadData       │
│                                                                                                  │
│   230 @cuda.bind("cuModuleLoadData", [ctypes.POINTER(CUmodule), ctypes.c_void_p], CUresult)      │
│   231 def cuModuleLoadData(data : bytes) -> CUmodule:                                            │
│   232 │   module = CUmodule()                                                                    │
│ ❱ 233 │   checkCUStatus(cuda.cuModuleLoadData(ctypes.byref(module), data))                       │
│   234 │   return module                                                                          │
│   235                                                                                            │
│   236 @cuda.bind("cuModuleUnload", [CUmodule], CUresult)                                         │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/library/cuda.py:216 in checkCUStatus          │
│                                                                                                  │
│   213                                                                                            │
│   214 def checkCUStatus(error : int) -> None:                                                    │
│   215 │   if error != CUDA_SUCCESS:                                                              │
│ ❱ 216 │   │   raise RuntimeError("CUDA Error: %s" % cuGetErrorString(error))                     │
│   217                                                                                            │
│   218 @cuda.bind("cuDriverGetVersion", [ctypes.POINTER(ctypes.c_int)], CUresult)                 │
│   219 def cuDriverGetVersion() -> int:                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA Error: no kernel image is available for execution on the device
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/ptuning/main.py:487 in <module>                                                            │
│                                                                                                  │
│   484                                                                                            │
│   485                                                                                            │
│   486 if __name__ == "__main__":                                                                 │
│ ❱ 487 │   main()                                                                                 │
│   488                                                                                            │
│                                                                                                  │
│ /data/ptuning/main.py:202 in main                                                                │
│                                                                                                  │
│   199 │                                                                                          │
│   200 │   if model_args.quantization_bit is not None:                                            │
│   201 │   │   print(f"Quantized to {model_args.quantization_bit} bit")                           │
│ ❱ 202 │   │   model = model.quantize(model_args.quantization_bit)                                │
│   203 │   if model_args.pre_seq_len is not None:                                                 │
│   204 │   │   # P-tuning v2                                                                      │
│   205 │   │   model = model.half()                                                               │
│                                                                                                  │
│ /home/jovyan/.cache/huggingface/modules/transformers_modules/model/modeling_chatglm.py:1190 in   │
│ quantize                                                                                         │
│                                                                                                  │
│   1187 │   │                                                                                     │
│   1188 │   │   self.config.quantization_bit = bits                                               │
│   1189 │   │                                                                                     │
│ ❱ 1190 │   │   self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=e  │
│   1191 │   │   │   │   │   │   │   │   │   │   │   **kwargs)                                     │
│   1192 │   │   return self                                                                       │
│   1193                                                                                           │
│                                                                                                  │
│ /home/jovyan/.cache/huggingface/modules/transformers_modules/model/quantization.py:155 in        │
│ quantize                                                                                         │
│                                                                                                  │
│   152 def quantize(model, weight_bit_width, empty_init=False, device=None):                      │
│   153 │   """Replace fp16 linear with quantized linear"""                                        │
│   154 │   for layer in model.layers:                                                             │
│ ❱ 155 │   │   layer.self_attention.query_key_value = QuantizedLinear(                            │
│   156 │   │   │   weight_bit_width=weight_bit_width,                                             │
│   157 │   │   │   weight=layer.self_attention.query_key_value.weight.to(torch.cuda.current_dev   │
│   158 │   │   │   bias=layer.self_attention.query_key_value.bias,                                │
│                                                                                                  │
│ /home/jovyan/.cache/huggingface/modules/transformers_modules/model/quantization.py:139 in        │
│ __init__                                                                                         │
│                                                                                                  │
│   136 │   │   │   self.weight_scale = weight.abs().max(dim=-1).values / ((2 ** (weight_bit_wid   │
│   137 │   │   │   self.weight = torch.round(weight / self.weight_scale[:, None]).to(torch.int8   │
│   138 │   │   │   if weight_bit_width == 4:                                                      │
│ ❱ 139 │   │   │   │   self.weight = compress_int4_weight(self.weight)                            │
│   140 │   │                                                                                      │
│   141 │   │   self.weight = Parameter(self.weight.to(device), requires_grad=False)               │
│   142 │   │   self.weight_scale = Parameter(self.weight_scale.to(device), requires_grad=False)   │
│                                                                                                  │
│ /home/jovyan/.cache/huggingface/modules/transformers_modules/model/quantization.py:78 in         │
│ compress_int4_weight                                                                             │
│                                                                                                  │
│    75 │   │   gridDim = (n, 1, 1)                                                                │
│    76 │   │   blockDim = (min(round_up(m, 32), 1024), 1, 1)                                      │
│    77 │   │                                                                                      │
│ ❱  78 │   │   kernels.int4WeightCompression(                                                     │
│    79 │   │   │   gridDim,                                                                       │
│    80 │   │   │   blockDim,                                                                      │
│    81 │   │   │   0,                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/kernels/base.py:48 in __call__                │
│                                                                                                  │
│   45 │   │   │   sharedMemBytes : int, stream : cudart.cudaStream_t, params : List[Any] ) ->     │
│   46 │   │   assert len(gridDim) == 3                                                            │
│   47 │   │   assert len(blockDim) == 3                                                           │
│ ❱ 48 │   │   func = self._prepare_func()                                                         │
│   49 │   │                                                                                       │
│   50 │   │   cuda.cuLaunchKernel(func,                                                           │
│   51 │   │   │   gridDim[0], gridDim[1], gridDim[2],                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/kernels/base.py:40 in _prepare_func           │
│                                                                                                  │
│   37 │   │   cudart.cudaSetDevice(curr_device)   # ensure cudart context                         │
│   38 │   │   if curr_device not in self._funcs:                                                  │
│   39 │   │   │   self._funcs[curr_device] = cuda.cuModuleGetFunction(                            │
│ ❱ 40 │   │   │   │   self._module.get_module(), self._func_name                                  │
│   41 │   │   │   )                                                                               │
│   42 │   │   return self._funcs[curr_device]                                                     │
│   43                                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/kernels/base.py:24 in get_module              │
│                                                                                                  │
│   21 │   │   curr_device = cudart.cudaGetDevice()                                                │
│   22 │   │   if curr_device not in self._module:                                                 │
│   23 │   │   │   Device(curr_device).use()   # force initialize context                          │
│ ❱ 24 │   │   │   self._module[curr_device] = cuda.cuModuleLoadData(self._code)                   │
│   25 │   │   return self._module[curr_device]                                                    │
│   26                                                                                             │
│   27                                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/library/base.py:94 in wrapper                 │
│                                                                                                  │
│   91 │   │   │   def decorator(f):                                                               │
│   92 │   │   │   │   @wraps(f)                                                                   │
│   93 │   │   │   │   def wrapper(*args, **kwargs):                                               │
│ ❱ 94 │   │   │   │   │   return f(*args, **kwargs)                                               │
│   95 │   │   │   │   return wrapper                                                              │
│   96 │   │   │   return decorator                                                                │
│   97                                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/library/cuda.py:233 in cuModuleLoadData       │
│                                                                                                  │
│   230 @cuda.bind("cuModuleLoadData", [ctypes.POINTER(CUmodule), ctypes.c_void_p], CUresult)      │
│   231 def cuModuleLoadData(data : bytes) -> CUmodule:                                            │
│   232 │   module = CUmodule()                                                                    │
│ ❱ 233 │   checkCUStatus(cuda.cuModuleLoadData(ctypes.byref(module), data))                       │
│   234 │   return module                                                                          │
│   235                                                                                            │
│   236 @cuda.bind("cuModuleUnload", [CUmodule], CUresult)                                         │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/cpm_kernels/library/cuda.py:216 in checkCUStatus          │
│                                                                                                  │
│   213                                                                                            │
│   214 def checkCUStatus(error : int) -> None:                                                    │
│   215 │   if error != CUDA_SUCCESS:                                                              │
│ ❱ 216 │   │   raise RuntimeError("CUDA Error: %s" % cuGetErrorString(error))                     │
│   217                                                                                            │
│   218 @cuda.bind("cuDriverGetVersion", [ctypes.POINTER(ctypes.c_int)], CUresult)                 │
│   219 def cuDriverGetVersion() -> int:                                                           │
╰─────────────────────────────────â────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA Error: no kernel image is available for execution on the device
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8425) of binary: /opt/conda/bin/python3.9
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-10_08:28:48
  host      : r64a78428ced2281ef01aef5b-gpu-jupyter-7d86bd58f9-gjjh9
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 8426)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-10_08:28:48
  host      : r64a78428ced2281ef01aef5b-gpu-jupyter-7d86bd58f9-gjjh9
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 8425)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### Expected Behavior

请帮我看一下上述报错是由于什么原因引起的？是配置问题还是环境问题？谢谢！
```
CUDA Error: no kernel image is available for execution on the device
```

### Steps To Reproduce

1. bash train.sh

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.9.7
- Transformers: 4.30.2
- PyTorch: 2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by super-wcg** [comment]
请问这个问题解决了么，同样的问题@zqkou

**Comment by zqkou** [comment]
> 请问这个问题解决了么，同样的问题@zqkou

目前还没有

**Comment by fatmind** [comment]
同问，这个问题解决了吗？

**Comment by fatmind** [comment]
@zqkou @super-wcg  去掉量化 --quantization_bit 4，成功了。
环境：Ubuntu、PyTorch:2.0.1、NVIDIA T4
但为什么去掉，就可以了，还不清楚。求大佬指点。

**Comment by zqkou** [comment]
去掉量化参数 --quantization_bit 4，是可以跑的，就是全精度参数tuning。

现在的问题就是如果想做量化参数的tuning，就会遇到上述的问题。目前在网上搜索得到的信息是我用的K80卡相关的量化的支持已经不在Torch默认包里了，需要从source编译torch。但是由于环境的问题我一直没成功。

**Comment by gavinju** [comment]
GPU下运行遇到同样的问题：CUDA Error: no kernel image is available for execution on the device。改成float()用CPU运行是正常的。请假大家，这个问题解决了吗？
