### ISSUE TITLE
[BUG/Help] Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by magicwang1111** [THUDM/ChatGLM2-6B#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "F:\ChatGLM2-6B\web_demo.py", line 6, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True, device='cuda')
  File "C:\Users\admin\anaconda3\envs\chatglm2\lib\site-packages\transformers\models\auto\auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\admin\anaconda3\envs\chatglm2\lib\site-packages\transformers\modeling_utils.py", line 2498, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b\a6d54fac46dff2db65d53416c207a4485ca6bd40\modeling_chatglm.py", line 767, in __init__
    self.transformer = ChatGLMModel(config, empty_init=empty_init, device=device)
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b\a6d54fac46dff2db65d53416c207a4485ca6bd40\modeling_chatglm.py", line 690, in __init__
    self.embedding = init_method(Embedding, config, **init_kwargs)
  File "C:\Users\admin\anaconda3\envs\chatglm2\lib\site-packages\torch\nn\utils\init.py", line 52, in skip_init
    return module_cls(*args, **kwargs).to_empty(device=final_device)
  File "C:\Users\admin\anaconda3\envs\chatglm2\lib\site-packages\torch\nn\modules\module.py", line 1024, in to_empty
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "C:\Users\admin\anaconda3\envs\chatglm2\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\admin\anaconda3\envs\chatglm2\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\admin\anaconda3\envs\chatglm2\lib\site-packages\torch\nn\modules\module.py", line 1024, in <lambda>
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "C:\Users\admin\anaconda3\envs\chatglm2\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

### Steps To Reproduce

1、conda create --name chatglm2 python=3.10
2、conda activate chatglm2
3、pip install -r requirements.txt

### Environment

```markdown
- OS:windows10
- Python:3.10
- Transformers:transformers==4.27.1
- PyTorch:2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
(chatglm2) F:\ChatGLM2-6B>python -c "import torch; print(torch.cuda.is_available())"
False
```

**Comment by magicwang1111** [comment]
(chatglm2) F:\ChatGLM2-6B>pip freeze | findstr torch==2.0
torch==2.0.1

**Comment by magicwang1111** [comment]
slove

**Comment by Sonnybear** [comment]
what did you do to solve this issue ?  thanks

**Comment by bxjxxyy** [comment]
> what did you do to solve this issue ? thanks
pip install -r requirements.txt  installed torch cpu version,not gpu version.
I got this problem too,uninstall cpu version then install gpu version.

**Comment by zhangqibupt** [comment]
I also run into this error, resolved by reinstalling, hope it would help.
```
pip uninstall torch
pip install torch torchvision torchaudio
```

**Comment by 523499159** [comment]
先卸载
pip uninstall torch torchvision torchaudio
在重新安装
pip install torch torchvision torchaudio
好用

**Comment by copybash** [comment]
我试过了，重装 torch torchvision torchaudio 依然是没用的，因为没有制定版本信息，和 pip install -r requirements.txt 安装的版本是一样的，问题并没有解决。

我试了以下方法，CUDA 虽然是可用了，但是 torch 的版本又太久了

#### 检查 CUDA 驱动版本
$ nvidia-smi.exe | grep --color "CUDA Version"
| NVIDIA-SMI 512.95       Driver Version: 512.95       CUDA Version: 11.6     |

#### 在 pytorch 官网找到使用 cuda 编译的版本
https://pytorch.org/get-started/previous-versions/

#### 安装，原本想安装 pytorch2.0 版本的，但是官网并没有
$ conda install pytorch==**1.13.0** torchvision==0.14.0 torchaudio==0.13.0 pytorch-cuda=**11.6** -c pytorch -c nvidia

#### 重新检测
$ python -c "import torch; print(torch.cuda.is_available())"
True

版本太旧了报错：ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.
